name: repro tp2

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps: 
    - uses: actions/checkout@v4
    
    - name: Build the Docker image then run the Docker container and save output to a file
      run: |
        docker build ./python --tag pythonTest:$(date +%s)
        docker run pythonTest ./python > output.txt
        cat output.txt
