name: repro tp2

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps: 
    - uses: actions/checkout@v4
    
    - name: Build the Docker image
      run: |
        docker build ./python --tag pythontest
        
    - name: Run the Docker container and save output to a file
        docker run pythontest > output.txt
        cat output.txt

    - name: Add, commit, and push the file with the results
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git add output.txt
        git commit -m "add result"
        
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: ${{ github.ref }}
